apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-app-juego
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: image-registry.openshift-image-registry.svc:5000/demo1-mtp/app-juego-db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: my_database
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: userpassword
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
